### ISSUE TITLE
UI element in the way

### ISSUE THREAD

**Issue by DaemosDaen** [Aroma1997/GPS#1]
I had a duh moment and posted in the comments thread instead of here:

GPS or Aroma1997core mod adds a compass and time in the lower left hand side of the screen, there is not indication of a way to move this element and it interferes with the default chat UI

Also can the clock be disabled?

**Comment by Aroma1997** [comment]
It was there in the original mod. I'll make it disablabe, though.

**Comment by Aroma1997** [comment]
Fixed in the new version of the GPS mod. It's only there, if you have an enabled GPS in your inventory.

**Comment by DaemosDaen** [comment]
Thank you.
