### ISSUE TITLE
Specteators showing up on GPS

### ISSUE THREAD

**Issue by MCEventHorizon** [Aroma1997/GPS#3]
Is it possible to add a config or something that disables spectators showing up on the GPS? I'm using it for a modded UHC pack that I made and spectators watching players show up on GPS which confuses players still in the game.

**Comment by Aroma1997** [comment]
Should be there in the next build.

**Comment by MCEventHorizon** [comment]
Is there an ETA for the next build?

**Comment by Aroma1997** [comment]
It's out already since about 10 days ago...

**Comment by MCEventHorizon** [comment]
Oh sorry, it version is labeled as beta, that's why I didn't see it on Twitch.
